node:
  switch01:
    mlag:
      address: 169.254.1.1/30
      backup-ip: 192.168.200.2
      members:
      - swp2
      peer-ip: 169.254.1.2
      sysmac: 44:38:39:FF:01:56
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    switching:
      bond01:
        members:
          - swp1
        mode: access
        vlans:
          - 100
    routing:
      lo:
      ospf:
        area:
        neighbors:
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
  switch02:
    mlag:
      address: 169.254.1.2/30
      backup-ip: 192.168.200.1
      members:
      - swp2
      peer-ip: 169.254.1.1
      sysmac: 44:38:39:FF:01:56
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    switching:
      bond01:
        members:
          - swp1
        mode: access
        vlans:
          - 100
    routing:
      lo:
      ospf:
        area:
        neighbors:
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
