- name: Simple Debug Script
  hosts: all
  gather_facts: yes

  tasks:
   - debug:
       msg: "{{ node[inventory_hostname].routing.svi }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.ospf.neighbors }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.lo | regex_replace('/32')}}"

   - debug:
       msg: "{{ item.ip }}"
     with_subelements:
       - "{{ node[inventory_hostname].routing.svi }}"
