- name: Simple Debug Script
  hosts: all
  gather_facts: yes

  tasks:
#   - debug:
#       msg: "{{ node[inventory_hostname].routing.svi }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.ospf.neighbors }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.lo | regex_replace('/32')}}"

   - debug:
       msg: "add interface {{ [ item ].vlan }}"
     with_items: "{{ node[inventory_hostname].routing.svi }}"
