- name: Simple Debug Script
  hosts: all
  gather_facts: yes

  tasks:
   - debug:
       msg: Ports {{ node[inventory_hostname].ports}}

   - debug:
       msg: add bond {{ item.key.value }} bond slaves {{ item.value.members }}
     with_dict:
      - "{{ node[inventory_hostname].mlag.interfaces }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.ospf.neighbors }}"

#   - debug:
#       msg: "{{ node[inventory_hostname].routing.lo | regex_replace('/32')}}"

#   - debug:
#       msg: "{{ item.value.ip }}"
#     with_dict:
#       - "{{ node[inventory_hostname]['routing']['svi'] }}"
